### ISSUE TITLE
Plan for serverless backlog

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#124]
Need to create a plan for the following issues on the content board:

- [ ] Issue 106 - [ [ serverless event stream processing ](https://github.com/IBM/cloud-patterns-development/issues/127) ] ? - Week 32
- [ ] Issue 151 - [ [ serverless mobile backend ](https://github.com/IBM/cloud-patterns-development/issues/128) ] Anton - Week 30 
- [ ] Issue 086 - [ [ serverless microservices backend ](https://github.com/IBM/cloud-patterns-development/issues/125 ) ] Andrea - Week 28
- [ ] Issue 094 - [ [ serverless webapp with cloud storage ](https://github.com/IBM/cloud-patterns-development/issues/126) ] Olaph  - Week 28
- [ ] Issue 081  - [ [ serverless image recognition ](https://github.com/IBM/cloud-patterns-development/issues/129) ] Anthony - Week 30??
