### ISSUE TITLE
Add DMP to Kubernetes journeys

### ISSUE THREAD

**Issue by loafyloaf** [IBM/cloud-patterns-development#27]
- [x] spring-boot-microservices-on-kubernetes
- [x] Kubernetes-container-service-Gitlab-sample [#53](https://github.com/IBM/Kubernetes-container-service-GitLab-sample/pull/53)
- [x] Scalable-WordPress-deployment-on-Kubernetes [#29](https://github.com/IBM/Scalable-WordPress-deployment-on-Kubernetes/pull/29)
- [x] Scalable-Cassandra-deployment-on-Kubernetes [#25](https://github.com/IBM/Scalable-Cassandra-deployment-on-Kubernetes/pull/25)
- [x] Java-MicroProfile-on-Kubernetes [#21](https://github.com/IBM/Java-MicroProfile-on-Kubernetes/pull/21)

**Comment by antonmc** [comment]
Would be good if this can be done during week 45 ( this week ) - they want to roll up data to the VPs next week.

**Comment by loafyloaf** [comment]
also, added this info to https://ibm.ent.box.com/notes/238314826590
